### ISSUE TITLE
Unauthorized to sign into Apple music via Cider

### ISSUE THREAD

**Issue by ArgonGaming** [ciderapp/Cider-2#369]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Latest

### Operating System Version

Windows 11

### Describe the Bug

Keep getting an "unauthorized login" error everytime I attempt to sign into Apple Music on Cider.

```
20LastFM.bfcd7f83.js:249  Uncaught DOMException: Blocked a frame with origin "https://tauri.localhost" from accessing a cross-origin frame.
    at https://tauri.localhost/assets/LastFM.bfcd7f83.js:249:3223
4musickit.js:28  Uncaught (in promise) AUTHORIZATION_ERROR: Unauthorized
    at https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js:28:232947
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$H (https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js:28:229853)
    at _next (https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js:28:230078)
11LastFM.bfcd7f83.js:249  Uncaught DOMException: Blocked a frame with origin "https://tauri.localhost" from accessing a cross-origin frame.
    at https://tauri.localhost/assets/LastFM.bfcd7f83.js:249:3223
musickit.js:28  Uncaught (in promise) AUTHORIZATION_ERROR: Unauthorized
    at https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js:28:232947
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$H (https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js:28:229853)
    at _next (https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js:28:230078)
```

### Steps to Reproduce

1. Install latest version of Cider on Windows Store
2. Attempt to sign in

**Comment by DeadFrostt** [comment]
Have you tried logging into https://beta.music.apple.com/ first then logging into Cider?

**Comment by ArgonGaming** [comment]
Did not work for me sadly

> Have you tried logging into https://beta.music.apple.com/ first then logging into Cider?

**Comment by coredev-uk** [comment]
If logging into the Apple Music site did not work it may be a fault with Apple then, or your network. I suggest reaching out to Apple support to get this resolved.

**Comment by ArgonGaming** [comment]
The site itself separately works, it's via the client that this errors

**Comment by coredev-uk** [comment]
You said it didn't work, but it does?

**Comment by ArgonGaming** [comment]
Logging into apple music on my browser alone works, going thru Cider to log in to apple music does not

**Comment by cryptofyre** [comment]
I personally have been unable to replicate the same behavior on any of our test beds so I'm unable to sum this up to anything besides your own firewall rules perhaps.
