### ISSUE TITLE
Song progress freezes after reordering songs in the queue

### ISSUE THREAD

**Issue by cr3eperall04** [ciderapp/Cider-2#490]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

Built on 9/22/2023, 12:27:31 AM | Quasar v2.12.6 | Electron   ceed39250d5f76c5bb7b5bc02978882ddd73c7b1

### Operating System Version

Arch 6.6.11-1-lts

### Describe the Bug

If i reorder the song in the queue this happens:
- The progress bar, the time and duration freeze
- The album art and the song nam freeze, they now change only if i change song manually
- The music keeps playing but sometimes a song gets played twice/it stops playing
- The mpris interface gets no updates
- If i request currentPlayingSong from the RPC (localhost:10769/currentPlayingSong) it returns Internal Server Error and this gets printed to stdout:
  ```
  Error: Uncaught Error: An object could not be cloned.
        at node:electron/js2c/renderer_init:2:16972
        at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:11161)
        at EventEmitter.emit (node:events:513:28)
        at Object.onMessage (node:electron/js2c/renderer_init:2:9264)
  ``` 
if i use chrome devtools via remote debugging this error is printed every 250ms: 
```
Uncaught (in promise) Error: An object could not be cloned.
    at Object.playbackTimeDidChange (MusicKit.77cc7c4e.js:1:18000)
    at MusicKit.77cc7c4e.js:1:10305
    at wrappedCallback (musickit.js:28:386813)
    at musickit.js:13:120989
    at Array.forEach (<anonymous>)
    at PubSub.publish (musickit.js:13:120977)
    at musickit.js:28:84671
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$14 (musickit.js:28:74001)
    at _next (musickit.js:28:74229)
```

### Steps to Reproduce

1. Have more than 2 songs in the queue
2. Open the queue and drag a song to change its place in the queue
3. Wait for the next song to play or press the next button

**Comment by cr3eperall04** [comment]
was fixed in cider 2.3.0
